---
type: showroom

default_width: 30
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: content

tabs:
  - name: Console
    url: 'https://console-openshift-console.${DOMAIN}'
  - name: Dev Hub
    url: 'https://developer-hub.${DOMAIN}'
  - name: GitLab
    url: 'https://gitlab.${DOMAIN}'
  - name: DevSpaces
    url: 'https://devspaces.${DOMAIN}'
  - name: OCP AI
    url: 'https://rhods-dashboard-redhat-ods-applications.${DOMAIN}'
  - name: Terminal
    url: '/terminal/'
